objects/Attendees__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Valid Email Address.</description>
        <inlineHelpText>This email will be use to contact the attendee.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <description>Object for events</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the location of the event.</description>
        <inlineHelpText>This is the location of the event.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name.</description>
        <inlineHelpText>This is the event name.</inlineHelpText>
        <label>Name</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organizer information.</description>
        <inlineHelpText>This is the person who will organize this event.</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>This is the start date of the event.</description>
        <inlineHelpText>This is the start date of the event.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event for Pro FIT</label>
    <nameField>
        <displayFormat>Event-{00000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <description>Object for events and its attendees</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>This field for the attendee.</description>
        <inlineHelpText>This field for the attendee.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendees__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_for_Pro_FIT__c</fullName>
        <description>This is the event.</description>
        <inlineHelpText>Name of the event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Organizer__c.object
<CustomObject>
    <description>Object for Event Organizers</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Needs to be valid email address</description>
        <inlineHelpText>This can be use for contacting the event organizer.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location of the organizer.</description>
        <inlineHelpText>This is the location of the organizer.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Event Organizers</relationshipLabel>
        <relationshipName>Event_Organizers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>This is for the City only.</description>
        <inlineHelpText>This is for the City only.</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>This field is for country only.</description>
        <inlineHelpText>Choose country where the address is located.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>This is for postal/ZIP code only.</description>
        <inlineHelpText>This field is for postal/ZIP code only.</inlineHelpText>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field is for state code only.</description>
        <inlineHelpText>If the address is in the US, please specify here which state.</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street address of the Event</description>
        <inlineHelpText>This field is only for Street</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Location Address Book</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventAttendeeHandler.cls
public class EventAttendeeHandler {
    public static void sendEmail(List<Event_Attendee__c> newRecordList ) {
        Set<Id> attendeesIdsSet = new Set<Id>();
        Set<Id> eventIdsSet = new Set<Id>();
        for(Event_Attendee__c ea : newRecordList){
            attendeesIdsSet.add(ea.Attendee__c);
            eventIdsSet.add(ea.Event_for_Pro_FIT__c);
        }
        Map<Id,Attendees__c> attendeeMap = new Map<Id,Attendees__c>( 
            [Select Id, Name, Email__c From Attendees__c WHERE  Id IN : attendeesIdsSet]
        );
        Map<Id, Event__c > eventMap = new Map<Id, Event__c > ( [Select Id, Name__c, Start__c, Organizer__c , Organizer__r.Name, Location__c , Location__r.Name, Location__r.City__c, Location__r.State__c, Location__r.Country__c, Location__r.Postal_Code__c, Location__r.Street__c FROM Event__c  WHERE ID IN: eventIdsSet]);
        System.debug('events: ' + eventMap);
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        for(Event_Attendee__c ea : newRecordList){
            Attendees__c att = attendeeMap.get(ea.Attendee__c);
            Event__c evt = eventMap.get(ea.Event_for_Pro_FIT__c);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Pass for the '+evt.Name__c);
            List<String> toAddress = new List<String>();
            toAddress.add(att.Email__c);
            mail.setToAddresses( toAddress );
            mail.setSenderDisplayName(evt.Organizer__r.Name);

            String locaton = 'https://www.google.com/maps/place/'+evt.Location__r.Street__c+' '+evt.Location__r.City__c+' '+evt.Location__r.State__c+' '+evt.Location__r.Country__c+' '+evt.Location__r.Postal_Code__c;
            System.debug('locations: ' + locaton);
            String hrefForLocation = '<a href="'+locaton+'"'+'target="_blank">here</a>';
            String emailBody = 'Dear '+ att.Name + ',<br/><br/>'+'Thank you for registering for <strong>'+evt.Name__c+'</strong> which will be organized on '+evt.Start__c.format('MMMM d, y EEEE')+' at '+evt.Start__c.format('H:mm a')+' and will be held in <strong>'+evt.Location__r.Name+'</strong>.<br/>We are excited to have you, see you in the event! <br/>You can find the location at Google Map by clicking '+hrefForLocation+'.<br/><br/><br/>Best,<br/>'+evt.Organizer__r.Name;
            mail.setHtmlBody(emailBody);
            emailList.add(mail);
        }
        List<Messaging.SendEmailResult> results =  Messaging.sendEmail(emailList, false);
        System.debug('Email Results: '+results);
        
    }
}