objects/Attendees__c.object
<CustomObject>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Name of attendee company.</description>
        <inlineHelpText>This is the current company of the attendee.</inlineHelpText>
        <label>Company Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Valid Email Address.</description>
        <inlineHelpText>This email will be use to contact the attendee.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location_Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This must be a valid address or location.</description>
        <inlineHelpText>This must be a valid address or location.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Valid phone number</description>
        <inlineHelpText>This phone number will be use to contact the attendee.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <description>Object for events</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the location of the event.</description>
        <inlineHelpText>This is the location of the event.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name.</description>
        <inlineHelpText>This is the event name.</inlineHelpText>
        <label>Name</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Event for Pro FIT</label>
    <nameField>
        <displayFormat>Event-{00000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <description>Object for events and its attendees</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>This field for the attendee.</description>
        <inlineHelpText>This field for the attendee.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendees__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_for_Pro_FIT__c</fullName>
        <description>This is the event.</description>
        <inlineHelpText>Name of the event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>This object is for Speakers and to their events</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>This is the name of the event assigned to the speaker.</description>
        <inlineHelpText>This is the name of the event assigned to the speaker.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>This is the speaker assigned to the event.</description>
        <inlineHelpText>This is the speaker assigned to the event.</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>This is for the City only.</description>
        <inlineHelpText>This is for the City only.</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>This field is for country only.</description>
        <inlineHelpText>Choose country where the address is located.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Landmark__c</fullName>
        <description>Nearest landmark</description>
        <inlineHelpText>Nearest landmark to this address.</inlineHelpText>
        <label>Landmark</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>This is for postal/ZIP code only.</description>
        <inlineHelpText>This field is for postal/ZIP code only.</inlineHelpText>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field is for state code only.</description>
        <inlineHelpText>If the address is in the US, please specify here which state.</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street address of the Event</description>
        <inlineHelpText>This field is only for Street</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Location Address Book</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <description>This object is for speakers</description>
    <fields>
        <fullName>Company__c</fullName>
        <description>This is the name of the company of the speaker.</description>
        <inlineHelpText>This is the name of the company of the speaker.</inlineHelpText>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>This email will be use to contact the speaker.</description>
        <inlineHelpText>This email will be use to contact the speaker.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>This phone number will be use to contact the speaker.</description>
        <inlineHelpText>This phone number will be use to contact the speaker.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EventDetailsClassController.cls
public with sharing class EventDetailsClassController {
    @AuraEnabled(cacheable=true)
    public static List<Event_Speaker__c> getSpeakers(String eventId){
        List<Event_Speaker__c> spkrList = [SELECT Id, Name, Event__c,Event__r.Name__c, Speaker__c, Speaker__r.Name, Speaker__r.Phone__c, Speaker__r.Email__c, Speaker__r.Company__c FROM Event_Speaker__c WHERE Event__c = :eventId]; 
        return spkrList;
    }

    @AuraEnabled(cacheable=true)
    public static Event__c getLocationDetails(String eventId){
        Event__c  evntRec = [SELECT Id, Name__c, Location__c, Location__r.Name, Location__r.City__c, Location__r.Country__c, Location__r.Landmark__c, Location__r.Postal_Code__c, Location__r.State__c, Location__r.Street__c FROM Event__c WHERE Location__c != :null AND Id = :eventId]; 
        return evntRec;
    }

    @AuraEnabled(cacheable=true)
    public static List<Event_Attendee__c> getAttendees(String eventId){
        List<Event_Attendee__c> evntAttendeeList = [SELECT Id, Name, Attendee__c, Event_for_Pro_FIT__c, Attendee__r.Name,Attendee__r.Phone__c, Attendee__r.Email__c, Attendee__r.Company_Name__c, Attendee__r.Location_Address_Book__c, Attendee__r.Location_Address_Book__r.Name FROM Event_Attendee__c WHERE Event_for_Pro_FIT__c = :eventId]; 
        return evntAttendeeList;
    }
  
}
    