objects/Attendees__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Valid Email Address.</description>
        <inlineHelpText>This email will be use to contact the attendee.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Valid phone number</description>
        <inlineHelpText>This phone number will be use to contact the attendee.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <description>Object for events</description>
    <fields>
        <fullName>End__c</fullName>
        <description>This is the end date of the event.</description>
        <inlineHelpText>This is the end date of the event.</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This is to identify if the event is live In-Person or via Virtual.</description>
        <inlineHelpText>This is to identify if the event is live In-Person or via Virtual.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To know if the event is live or not.</description>
        <inlineHelpText>Check if the event is live.</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Seats available</description>
        <inlineHelpText>Numbers of the guests.</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name.</description>
        <inlineHelpText>This is the event name.</inlineHelpText>
        <label>Name</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organizer information.</description>
        <inlineHelpText>This is the person who will organize this event.</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>This is the start date of the event.</description>
        <inlineHelpText>This is the start date of the event.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event for Pro FIT</label>
    <nameField>
        <displayFormat>Event-{00000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <description>Object for events and its attendees</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>This field for the attendee.</description>
        <inlineHelpText>This field for the attendee.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendees__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_for_Pro_FIT__c</fullName>
        <description>This is the event.</description>
        <inlineHelpText>Name of the event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Organizer__c.object
<CustomObject>
    <description>Object for Event Organizers</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Needs to be valid email address</description>
        <inlineHelpText>This can be use for contacting the event organizer.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Valid phone number.</description>
        <inlineHelpText>This can be use for contacting the event organizer.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventAttendeeTest.cls
@isTest
public class EventAttendeeTest {
    static Id createTestEventOrg(){    
        Event_Organizer__c evtOrg = new Event_Organizer__c();
        evtOrg.Name = 'George Matt';
        evtOrg.Phone__c = '999999';
        evtOrg.Email__c = 'arielayenegrido@gmail.com';
        insert evtOrg;
        return evtOrg.Id;
    }
    static Id createTestEvent(){    
        Event__c evt = new Event__c();
        evt.Name__c = 'Test Event';
        evt.Organizer__c = createTestEventOrg();
        evt.Event_Type__c = 'Virtual';
        evt.Max_Seats__c = 199;
        evt.Live__c = true;
        evt.Start__c = System.now()+1;
        evt.End__c = System.now()+2;
        insert evt;
        return evt.Id;
    }
    static Id createTestAttendee(){    
        Attendees__c att = new Attendees__c();
        att.Name = 'John Cons';
        att.Phone__c = '12312';
        att.Email__c = 'arielayenegrido@gmail.com';
        insert att;
        return att.Id;
    }
    
    @isTest
    static void sendEmailTest(){
        Test.startTest();
        Event_Attendee__c evtAtt = new Event_Attendee__c();
        evtAtt.Attendee__c = createTestAttendee();
        evtAtt.Event_for_Pro_FIT__c = createTestEvent();
        evtAtt.Name = 'Test EA';
        insert evtAtt;
        List <Event_Attendee__c> evtAttRecord = [Select Id, Name, Attendee__c, Event_for_Pro_FIT__c from Event_Attendee__c where Id =:evtAtt.Id];
        EventAttendeeHandler.sendEmail(evtAttRecord);
        Test.stopTest();
        System.assertEquals('Test EA', evtAtt.Name);
    }
}