objects/Event__c.object
<CustomObject>
    <description>Object for events</description>
    <fields>
        <fullName>End__c</fullName>
        <description>This is the end date of the event.</description>
        <inlineHelpText>This is the end date of the event.</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>This is the start date of the event.</description>
        <inlineHelpText>This is the start date of the event.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event for Pro FIT</label>
    <nameField>
        <displayFormat>Event-{00000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>This object is for Speakers and to their events</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>This is the name of the event assigned to the speaker.</description>
        <inlineHelpText>This is the name of the event assigned to the speaker.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>This is the speaker assigned to the event.</description>
        <inlineHelpText>This is the speaker assigned to the event.</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <description>This object is for speakers</description>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EventSpeakerAlreadyHaveSameEvent.cls
public with sharing class EventSpeakerAlreadyHaveSameEvent {
    public static void CheckEventSpeaker(List<Event_Speaker__c> evtSpeakerList) {
        Set<Id> eventId = new Set<Id>();
        Set<Id> eventSpeakerId = new Set<Id>();
        for(Event_Speaker__c evntSpkr : evtSpeakerList){
            eventId.add(evntSpkr.Event__c);
            eventSpeakerId.add(evntSpkr.Speaker__c);
        }
        Map<Id, DateTime> startDateEvent = new Map<Id, DateTime>();
        Map<Id, DateTime> endDateEvent = new Map<Id, DateTime>();

        List<Event__c> relatedEventList = [Select Id, Name,Start__c,End__c From Event__c 
        Where Id IN: eventId];
        for(Event__c evt : relatedEventList ){
            startDateEvent.put(evt.Id, evt.Start__c);
            endDateEvent.put(evt.Id, evt.End__c);
        }
        List<Event_Speaker__c> relatedEventSpeakerList = [ SELECT Id, Event__c, Speaker__c,Event__r.Start__c,Event__r.End__c From Event_Speaker__c WHERE Speaker__c IN : eventSpeakerId]; 
        for(Event_Speaker__c evntSpkr : evtSpeakerList){
            DateTime startTime = startDateEvent.get(evntSpkr.Event__c);
            DateTime endTime = endDateEvent.get(evntSpkr.Event__c);
            for(Event_Speaker__c rS: relatedEventSpeakerList) {
                if((rS.Event__r.Start__c < endTime && rS.Event__r.End__c > endTime)||
                (rS.Event__r.Start__c < startTime && rS.Event__r.End__c > startTime)||
                (rS.Event__r.Start__c >= startTime && rS.Event__r.End__c <= endTime)) {
                        evntSpkr.Speaker__c.addError('The Speaker has a existing event that overlap the schedule of this event.');
                }
            }
        }
    }
}