objects/Event__c.object
<CustomObject>
    <description>Object for events</description>
    <fields>
        <fullName>End__c</fullName>
        <description>This is the end date of the event.</description>
        <inlineHelpText>This is the end date of the event.</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This is to identify if the event is live In-Person or via Virtual.</description>
        <inlineHelpText>This is to identify if the event is live In-Person or via Virtual.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To know if the event is live or not.</description>
        <inlineHelpText>Check if the event is live.</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Seats available</description>
        <inlineHelpText>Numbers of the guests.</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name.</description>
        <inlineHelpText>This is the event name.</inlineHelpText>
        <label>Name</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organizer information.</description>
        <inlineHelpText>This is the person who will organize this event.</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>This is the start date of the event.</description>
        <inlineHelpText>This is the start date of the event.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of teh event.</description>
        <inlineHelpText>This is to identify the status of the event.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Post Poned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event for Pro FIT</label>
    <nameField>
        <displayFormat>Event-{00000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UpdateEventStatusBatchTest.cls
@isTest
public class UpdateEventStatusBatchTest {
    public static testMethod void testUpdateBatch(){
        List<Event__c> listEvent = new List<Event__c>();
        for(Integer i=1; i<= 50; i++){
            Event__c event = new Event__c(
                Name__c = 'Test Event #'+i,
                Max_Seats__c  = 4,
                Live__c = false,
                Organizer__c = null,
                Status__c = 'In Progress',
                Event_Type__c = 'Virtual',
                Start__c = datetime.newInstance(2020, 12, 01, 11, 0, 0),
                End__c  = datetime.newInstance(2020, 12, 02, 13, 0, 0)
            );
            listEvent.add(event);
        }
        insert listEvent;
        Test.startTest();
        Database.executeBatch(new UpdateEventStatusBatch(), 100);
        Test.stopTest();
        System.AssertEquals(database.countquery('SELECT COUNT() From Event__c Where Status__c = \'Deleted\''), 50); 
    }
}