objects/Event__c.object
<CustomObject>
    <description>Object for events</description>
    <fields>
        <fullName>End__c</fullName>
        <description>This is the end date of the event.</description>
        <inlineHelpText>This is the end date of the event.</inlineHelpText>
        <label>End Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This is to identify if the event is live In-Person or via Virtual.</description>
        <inlineHelpText>This is to identify if the event is live In-Person or via Virtual.</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To know if the event is live or not.</description>
        <inlineHelpText>Check if the event is live.</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Seats available</description>
        <inlineHelpText>Numbers of the guests.</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Event Name.</description>
        <inlineHelpText>This is the event name.</inlineHelpText>
        <label>Name</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>This is the start date of the event.</description>
        <inlineHelpText>This is the start date of the event.</inlineHelpText>
        <label>Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of teh event.</description>
        <inlineHelpText>This is to identify the status of the event.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Post Poned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event for Pro FIT</label>
    <nameField>
        <displayFormat>Event-{00000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventDetailsRestService_Test.cls
@istest
public with sharing class EventDetailsRestService_Test {
    static Id createEventTestRecord(){
        Event__c evt = new Event__c();
        evt.Name__c = 'Test REST Service';
        evt.Start__c = System.today()+1;
        evt.End__c = System.today()+2;
        evt.Event_Type__c ='Virtual';
        evt.Live__c = true;
        evt.Status__c = 'Created';
        evt.Max_Seats__c = 1;
        insert evt;
        return evt.Id;
    }
    @IsTest
    static void doGetTest(){
        Test.startTest();
        Id EventId =  createEventTestRecord();
        RestRequest req = new RestRequest();
        req.requestURI = 'https://stefaniniconsultoriaeassessoriaemi--prjsandbox.my.salesforce.com/services/apexrest/api/Event__c/'+EventId;
        req.httpMethod = 'GET';
        RestContext.request = req;
        Event__c evt = EventDetailsRestService.doGetEvt();
        Test.stopTest();
        System.assertEquals(EventId, evt.Id);
    }
}