objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>This is for the City only.</description>
        <inlineHelpText>This is for the City only.</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>This field is for country only.</description>
        <inlineHelpText>Choose country where the address is located.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>United States of America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Zip_correct__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is to identify if the Zip on the location was verified.</description>
        <inlineHelpText>If this field is checked, it means that the zip on this location was verified.</inlineHelpText>
        <label>Is Zip correct?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>This is for postal/ZIP code only.</description>
        <inlineHelpText>This field is for postal/ZIP code only.</inlineHelpText>
        <label>Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>This field is for state code only.</description>
        <inlineHelpText>If the address is in the US, please specify here which state.</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street address of the Event</description>
        <inlineHelpText>This field is only for Street</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to specify if the event is Verified.</description>
        <inlineHelpText>Check this if the Event was Verified.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
    <label>Location Address Book</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/VerifyLocation_Test.cls
@isTest
public with sharing class VerifyLocation_Test {
    public static testMethod void testZip(){
        Location__c loc = new Location__c(
            Name = '3301 South Greenfield Rd',
            Street__c = '3301 South Greenfield Rd',
            City__c = 'Gilbert',
            State__c = 'AZ',
            Postal_Code__c = '85297',
            Country__c = 'United States of America',
            Is_Zip_correct__c = false
        );

        insert loc;

        Test.setMock(HttpCalloutMock.class, new ZipCalloutMock());
        Test.startTest();
        VerifyLocation.zipCodeCallOut(''+loc.Id+'');
        Test.stopTest();

        Location__c verifiedZipCode = [Select Is_Zip_correct__c from Location__c where Id =: loc.Id];
        System.debug('Is_Zip_correct__c boolean value: ' + verifiedZipCode.Is_Zip_correct__c);
        System.assertEquals(true, verifiedZipCode.Is_Zip_correct__c);

    }
    public static testMethod void testLoc(){
        Location__c loc = new Location__c(
            Name = '3301 South Greenfield Rd',
            Street__c = '3301 South Greenfield Rd',
            City__c = 'Gilbert',
            State__c = 'AZ',
            Postal_Code__c = '85297',
            Country__c = 'United States of America',
            Verified__c = false
        );

        insert loc;

        Test.setMock(HttpCalloutMock.class, new LocationMockCallout());
        Test.startTest();
        VerifyLocation.locationCallout(''+loc.Id+'');
        Test.stopTest();

        Location__c verifiedStreet = [Select Verified__c from Location__c where Id =: loc.Id];
        System.debug('Verified__c boolean value: ' + verifiedStreet.Verified__c);
        System.assertEquals(true, verifiedStreet.Verified__c);
    }
}